export const LOAD_TOKEN = 'LOAD_TOKEN';

export const CLEAR_TOKEN = 'CLEAR_TOKEN';

export const SET_LOADING = 'SET_LOADING';
export const ASYNC_FACEBOOK_LOGIN = 'ASYNC_FACEBOOK_LOGIN';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';

export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';

export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';

export const FACEBOOK_LOGOUT_SUCCESS = 'FACEBOOK_LOGOUT_SUCCESS';

export const FACEBOOK_LOGOUT_FAIL = 'FACEBOOK_LOGOUT_FAIL';

// JOBBA ACTIONS

export const LOAD_JOBS = 'LOAD_JOBS';
export const ASYNC_FETCH_JOBS = 'ASYNC_FETCH_JOBS';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_SAVED_JOB = 'SET_SAVED_JOB';

export const CLEAR_SAVED_JOB = 'CLEAR_SAVED_JOB';

export const CLEAR_ALL_SAVED_JOBS = 'CLEAR_ALL_SAVED_JOBS';

export const ASYNC_LOCAL_STORAGE_SAVE = 'ASYNC_LOCAL_STORAGE_SAVE';
export const ASYNC_LOCAL_STORAGE_LOAD = 'ASYNC_LOCAL_STORAGE_LOAD';
