module.exports.LOAD_TOKEN = 'LOAD_TOKEN';
module.exports.SET_LOADING = 'SET_LOADING';
module.exports.ASYNC_FACEBOOK_LOGIN = 'ASYNC_FACEBOOK_LOGIN';
module.exports.SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';


// // module.exports= ACTION_TYPE = 'ACTION_TYPE';
// // Export these Action Type strings from this file. Reducers and Actions that require them will be protected from typos this way.
//
// module.exports.SET_AUTH_EMAIL = 'SET_AUTH_EMAIL';
// module.exports.SET_AUTH_PASSWORD = 'SET_AUTH_PASSWORD';
// module.exports.CLEAR_AUTH = 'CLEAR_AUTH';
//
// module.exports.LOAD_USER_EMAIL = 'LOAD_USER_EMAIL';
// module.exports.LOAD_USER_ID = 'LOAD_USER_ID';
// module.exports.LOAD_USER_NAME = 'LOAD_USER_NAME';
// module.exports.LOAD_USER_ADDRESS = 'LOAD_USER_ADDRESS';
// module.exports.LOAD_USER_PHONE = 'LOAD_USER_PHONE';
// module.exports.LOAD_USER_ORDERS = 'LOAD_USER_ORDERS';
// module.exports.LOAD_USER_FAVOURITES = 'LOAD_USER_FAVOURITES';
// module.exports.CLEAR_USER = 'CLEAR_USER';
//
// module.exports.SET_ACTIVE_ORDER_USERID = 'SET_ACTIVE_ORDER_USERID';
// module.exports.SET_ACTIVE_ORDER_CONTENTS = 'SET_ACTIVE_ORDER_CONTENTS';
// module.exports.SET_ACTIVE_ORDER_NOTES = 'SET_ACTIVE_ORDER_NOTES';
// module.exports.SET_ACTIVE_ORDER_TOTAL_PRICE = 'SET_ACTIVE_ORDER_TOTAL_PRICE';
// module.exports.SET_ACTIVE_ORDER_ADDRESS = 'SET_ACTIVE_ORDER_ADDRESS';
// module.exports.SET_ACTIVE_ORDER_PHONE = 'SET_ACTIVE_ORDER_PHONE';
// module.exports.CLEAR_ACTIVE_ORDER = 'CLEAR_ACTIVE_ORDER';
//
// module.exports.LOAD_ITEMS = 'LOAD_ITEMS';
// module.exports.CLEAR_ITEMS = 'CLEAR_ITEMS';
//
// module.exports.LOAD_ACTIVE_ITEM = 'LOAD_ACTIVE_ITEM';
// module.exports.CLEAR_ACTIVE_ITEM = 'CLEAR_ACTIVE_ITEM';
//
// module.exports.SET_ITEM_QUERY_NAME = 'SET_ITEM_QUERY_NAME';
// module.exports.SET_ITEM_QUERY_INGREDIENTS = 'SET_ITEM_QUERY_INGREDIENTS';
// module.exports.SET_ITEM_QUERY_TYPE = 'SET_ITEM_QUERY_TYPE';
// module.exports.SET_ITEM_QUERY_DIETARY_ABBREVIATIONS = 'SET_ITEM_QUERY_DIETARY_ABBREVIATIONS';
// module.exports.SET_ITEM_QUERY_PRICE_MIN = 'SET_ITEM_QUERY_PRICE_MIN';
// module.exports.SET_ITEM_QUERY_PRICE_MAX = 'SET_ITEM_QUERY_PRICE_MAX';
// module.exports.SET_ITEM_QUERY_IN_STOCK = 'SET_ITEM_QUERY_IN_STOCK';
// module.exports.CLEAR_ITEM_QUERY = 'CLEAR_ITEM_QUERY';
//
// module.exports.ASYNC_START_REGISTER_USER = 'ASYNC_START_REGISTER_USER';
// module.exports.ASYNC_START_LOGGING_IN_USER = 'ASYNC_START_LOGGING_IN_USER';
// module.exports.ASYNC_START_QUERYING_ITEMS = 'ASYNC_START_QUERYING_ITEMS';
// module.exports.ASYNC_START_FETCHING_ITEMS = 'ASYNC_START_FETCHING_ITEMS';
// module.exports.ASYNC_START_PLACING_ORDER = 'ASYNC_START_PLACING_ORDER';
// module.exports.ASYNC_START_UPDATING_ORDER = 'ASYNC_START_UPDATING_ORDER';
// module.exports.ASYNC_START_UPDATING_USER = 'ASYNC_START_UPDATING_USER';
